### ISSUE TITLE
Rename devise-passkeys modules and concerns

### ISSUE THREAD

**Issue by heliocola** [ruby-passkeys/devise-passkeys-template#8]
Issue: ruby-passkeys gem got the naming convention updated to fix a few inconsistencies.
Ref: 
* https://github.com/ruby-passkeys/devise-passkeys/issues/4
* https://github.com/ruby-passkeys/devise-passkeys/pull/7

Summary of changes needed:
* Devise::Passkeys::Controllers::Concerns::PasskeyReauthentication -> Devise::Passkeys::Controllers::Concerns::Reauthentication

Once the new release of devise-passkeys is pushed to Rubygems, we can start updating it here.

**Comment by tcannonfodder** [comment]
I _think_ we're good with the release of 0.2.0. Closing; but feel free to reopen if I missed something
