### ISSUE TITLE
Dig into CSRF issues

### ISSUE THREAD

**Issue by tcannonfodder** [ruby-passkeys/devise-passkeys-template#9]
Today I ran some CSRF issues when actually making passkeys requests for:
- Adding a new passkey
- Updating a user

My guess is that it's something related to the reauthentication flow? I don't know yet, I need to dig in further.

I hadn't run into this before, my guess is that it's caused by a Rails or a Devise update

**Comment by tcannonfodder** [comment]
@heliocola Have you run into this?

**Comment by heliocola** [comment]
Yes I did run into it while trying out in this app, and in another app I've worked in the past few weeks.
I did do some digging into it, but I was not able to fix yet.

If you want, I can look into it and try to propose a solution.

**Comment by tcannonfodder** [comment]
That would be a huge help. I will try to look into it as well

**Comment by heliocola** [comment]
@tcannonfodder : Ok! I've found a work around... but it is late for me now, so I will create a draft PR.
And tomorrow I will try to test this with the devise-passkeys-template app.

What is happening is that the CSRF token is becoming old, after passkeys new challenge and authentication HTTP POSTs.

**Comment by tcannonfodder** [comment]
Sounds good! Thanks so much for digging into this! 💪

**Comment by tcannonfodder** [comment]
The fix has been merged in the `devise-passkeys` repo, but we haven't cut the latest version yet. Will close out this issue once the next version is released. https://github.com/ruby-passkeys/devise-passkeys/pull/45

In the meantime, folks can use the `main` branch directly if they need a fix before the new version is cut

**Comment by tcannonfodder** [comment]
`devise-passkeys` 0.2.0 has been released: https://github.com/ruby-passkeys/devise-passkeys/releases/tag/v0.2.0
